# Generated by Django 4.0 on 2022-03-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('Instagram', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('confirm', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('type', models.CharField(choices=[('Influencer', 'Influencer'), ('Manufacture', 'Manufacture'), ('Sponsor', 'Sponsor')], default='Influencer', max_length=11)),
            ],
        ),
    ]
