# Generated by Django 4.0 on 2022-03-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='confirm',
        ),
    ]
