# Generated by Django 4.0 on 2022-03-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_createuser_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='Instagram',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
