# Generated by Django 4.0 on 2022-04-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_createuser_instagram_alter_createuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instagram', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('Influencer', 'Influencer'), ('Manufacture', 'Manufacture'), ('Sponsor', 'Sponsor')], default='Influencer', max_length=11)),
            ],
        ),
    ]
