# Generated by Django 4.0 on 2022-04-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_createuser_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Instagram',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Influencer', 'Influencer'), ('Manufacture', 'Manufacture'), ('Sponsor', 'Sponsor')], default='Influencer', max_length=11, null=True),
        ),
    ]
