# Generated by Django 4.0 on 2022-06-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_request_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='no description!', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
